---

# docker compose up --build


services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    restart: always


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    stdin_open: true
    develop:
      watch:
        - action: rebuild
          path: frontend
#          target: /src/web
          ignore:
            - ./frontend/node_modules/
