
# Models for Wather api calls:
# https://docs.pydantic.dev/latest/integrations/datamodel_code_generator/

# generated by datamodel-codegen:
#   filename:  out.json
#   timestamp: 2024-03-27T21:02:45+00:00


from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Coord(BaseModel):
    lon: float
    lat: float


class WeatherItem(BaseModel):
    id: int
    main: str
    description: str
    icon: str


class Main(BaseModel):
    temp: float
    feels_like: float
    temp_min: float
    temp_max: float
    pressure: int
    humidity: int


class Wind(BaseModel):
    speed: float
    deg: int
    gust: float


class Clouds(BaseModel):
    all: int


class Sys(BaseModel):
    type: int
    id: int
    country: str
    sunrise: int
    sunset: int


class Weather(BaseModel):
    coord: Coord
    weather: List[WeatherItem]
    base: str
    main: Main
    visibility: int
    wind: Wind
    clouds: Clouds
    dt: int
    sys: Sys
    timezone: int
    id: int
    name: str
    cod: int
